### PR TITLE
Pulls/2.0/dependency debug

### LINKED ISSUE #22: Internal identifiers are exposed as prefix and suffix to element attributes.
A great example: https://github.com/silverstripe/silverstripe-html5/issues/19#issuecomment-374423237

e.g. `<section class="hero" style="background-image: url('html5-dom-document-internal-entity2-039-endassets/1c0d50c946/before-after.jpghtml5-dom-document-internal-entity2-039-end');">`

This is since the change of library introduced at ebba830

### PR DESCRIPTION
**Pull request by NightJar**
Go back to the original parser as it does not cause conflicts with the rest of the framework.
We can look at going back to an updated library when we drop support for PHP 5.6, or core stops having issues by way of integration between the shortcode parser and html5 value.

Resolves #22

### CODE REVIEW

**Comment by robbieaverill** [comment]
Minor phpcs violation needs to be fixed

**Review by robbieaverill — APPROVED** [review]
Nice. Just need to fix phpcs and good to merge on green

**Comment by NightJar** [comment]
Yeah, I'm trying to fix the phpcs thing, interesting that running `phpcs` doesn't pick anything up on my local :/

**Comment by robbieaverill** [comment]
phpcs in Travis was 3.2.3, you might need to update your local version

**Comment by NightJar** [comment]
Also 3.2.3 - a fresh requirement I had to include directly just now to test that it wasn't a version issue.
I thought it must be some config, but even when I directed to the framework standard it passed... 🤷‍♂️

**Review by robbieaverill — CHANGES_REQUESTED** [review]
Nice, can you please the readme too?

**Comment by NightJar** [comment]
Ah yep, whoops, nice catch :)

**Review by robbieaverill — APPROVED** [review]

**Comment by robbieaverill** [comment]
I think since we're changing dependencies that it should be a minor release, so we should release this change as 2.1.0 instead of 2.0.1. There are some other patch commits that could be released in 2.0.1 and/or merged up first too.

**Pull request merged**
